services:
  - type: web
    name: cashlog-web
    env: node
    rootDir: .
    buildCommand: corepack enable && pnpm install --frozen-lockfile  && pnpm run build && echo "BUILD DONE" && ls -R dist
    startCommand: pnpm run start
    envVars:
      - key: NODE_VERSION
        value: 20